### ISSUE TITLE
ckeditor full feature

### ISSUE THREAD

**Issue by Canhamateur** [UniSharp/laravel-ckeditor#12]
I really like your package, i have used it for all my projects. Could you please update ckeditor to lastest version? 
I want full controll in toolbar: http://ckeditor.com/demo#full 
Pls see link: http://cdn.ckeditor.com/4.5.10/standard-all/ckeditor.js
/*
Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
For licensing, see LICENSE.md or http://ckeditor.com/license
*/

Thank you so much :) !!!!!

**Comment by akitengineer** [comment]
+subscribing

**Comment by youchenlee** [comment]
Thank you / Sorry for late.
Actually we did nothing but wrap CKEditor into laravel. It's only a tiny work. The tough jobs are done by the CKEditor Team.

I published a pre-release for CKEditor 4.6.2 ( https://github.com/UniSharp/laravel-ckeditor/releases/tag/4.6.2-pre )

Will change it to the official release after a few tests.

**Comment by youchenlee** [comment]
BTW, Instead of using this package, I recommend just follow [the official CKEditor installation instructions with package managers](http://docs.ckeditor.com/#!/guide/dev_package_managers)
