### ISSUE TITLE
not working with laravel5.4

### ISSUE THREAD

**Issue by yingjun** [UniSharp/laravel-ckeditor#15]
Please do not report issues in CKEditor. The correct location of CKEditor issue tracker is: http://dev.ckeditor.com/

**Comment by youchenlee** [comment]
@yingjun would you please provide us the error logs?

Thanks for the reporting.

**Comment by yingjun** [comment]
Call to undefined method Illuminate\Foundation\Application::share() in vendor/unisharp/laravel-filemanager/src/LaravelFilemanagerServiceProvider.php:47

sorry it was filemanager

**Comment by youchenlee** [comment]
@yingjun thanks. would you please give filemanager [1.6.4](https://github.com/UniSharp/laravel-filemanager/releases/tag/1.6.4) a try? It should be accessible by composer right now.
