### ISSUE TITLE
Ckeditor : Text showing in one line with scroll

### ISSUE THREAD

**Issue by Harrrrry** [UniSharp/laravel-ckeditor#2]
Hyy, When i insert text into ckeditor its showing good and added into database but in edit form it showing all text into one line with scroll.

Note : I notice that this issue is only with Firefox browser

in add form it showing like this
![ckeditortext jpeg](https://cloud.githubusercontent.com/assets/14884583/10839503/bc62edec-7efa-11e5-85d1-9b292c8eea6d.png)

in edit form it showing like this
![ckeditorwrong jpeg](https://cloud.githubusercontent.com/assets/14884583/10839506/c3730ac2-7efa-11e5-829b-e7787a425de8.png)

**Comment by Harrrrry** [comment]
is there any way to show same in edit also, please help.

**Comment by FreedomKnight** [comment]
can you check is there any \r in your database ?
i think i need some data which in your db to help you

**Comment by Harrrrry** [comment]
@FreedomKnight  thanks for reply

my content store in data base like this

<p>Next,&nbsp;select&nbsp;the&nbsp;three&nbsp;paragraphs&nbsp;and&nbsp;choose&nbsp;Table&nbsp;|&nbsp;Convert&nbsp;|&nbsp;Text&nbsp;to&nbsp;Table.&nbsp;Set&nbsp;the&nbsp;number&nbsp;of&nbsp;columns&nbsp;to&nbsp;3,&nbsp;make&nbsp;sure&nbsp;the&nbsp;conversion&nbsp;is&nbsp;set&nbsp;to&nbsp;separate&nbsp;text&nbsp;at&nbsp;paragraphs,&nbsp;and&nbsp;choose&nbsp;OK.&nbsp;This&nbsp;will&nbsp;produce&nbsp;a&nbsp;one-row,&nbsp;three-cell&nbsp;table&nbsp;with&nbsp;text&nbsp;in&nbsp;each&nbsp;cell&nbsp;and&nbsp;the&nbsp;row&nbsp;selected.&nbsp;Copy&nbsp;the&nbsp;selected&nbsp;text&nbsp;and&nbsp;create&nbsp;as&nbsp;many&nbsp;rows&nbsp;as&nbsp;you&nbsp;need&nbsp;by&nbsp;pasting&nbsp;them&nbsp;in.</p>

**Comment by youchenlee** [comment]
Hi @Harrrrry ,
Does this issue exists (in firefox) when you install CKEditor directly from the official website?
 http://ckeditor.com
