### ISSUE TITLE
config

### ISSUE THREAD

**Issue by rivory** [UniSharp/laravel-ckeditor#29]
Please do not report issues in CKEditor. The correct location of CKEditor issue tracker is: http://dev.ckeditor.com/

**Comment by woosshie** [comment]
i was followed install instruction. 
but i got this warning. 

************************
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
************************
does anyone knows how to solve this problem?

composer require unisharp/laravel-ckeditor
.....
Package operations: 1 install, 0 updates, 0 removals
  - Installing unisharp/laravel-ckeditor (4.7.2): Downloading (100%)
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
......
