### ISSUE TITLE
not working with laravel 5.2.10

### ISSUE THREAD

**Issue by facilinfo** [UniSharp/laravel-ckeditor#4]
Hello, 

It seems it doesn't work because of illuminate/support version.

Thanks.

**Comment by midium** [comment]
It should just related to the composer.json require value. Changing it to ">=5.0.0" should make it compatible with versions greater that 5.0 and so compatible also with 5.2.*

**Comment by midium** [comment]
I confirm, I've forked this and make just some little changes (main one that described before) and I've been able to get it working on Laravel 5.2. Feel free to use my fork if you need it asap.

**Comment by youchenlee** [comment]
Thanks @facilinfo, @midium and @lokimo. It's now support laravel 5.2
Sorry for my late reply, it has been a long holiday here.

**Comment by youchenlee** [comment]
Bump version to 4.5.7 for laravel 5.2 support.
https://packagist.org/packages/unisharp/laravel-ckeditor#4.5.7
