### ISSUE TITLE
Update CKeditor for 4.14.0

### ISSUE THREAD

**Issue by aristidesneto** [UniSharp/laravel-ckeditor#49]
Hi, I would like to contribute to the project, I want to update the project to 4.14.0, but I did not understand how to do it.

Could someone explain how update the version?

Tanks.

**Comment by StApostol** [comment]
@aristidesneto This project has little support. You can try your hand at this repository [https://github.com/dev-techguy/laravel-ckeditor](https://github.com/dev-techguy/laravel-ckeditor)

**Comment by aristidesneto** [comment]
> @aristidesneto This project has little support. You can try your hand at this repository https://github.com/dev-techguy/laravel-ckeditor

Thanks @StApostol
