### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by premier213** [UniSharp/laravel-ckeditor#6]
hi my use this package for laravel 5.2 and when add 

`    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
    <script>
        $('textarea').ckeditor();
        // $('.textarea').ckeditor(); // if class is prefered.
    </script>`

to my page not work

**Comment by youchenlee** [comment]
@premier213 
Please provide more info, what's your installation steps? Any errors during installation? Any related errors in the browser console?

**Comment by premier213** [comment]
![2016-02-21_22-33-59](https://cloud.githubusercontent.com/assets/4321174/13204679/61775a44-d8eb-11e5-864d-b9c789a28544.jpg)

**Comment by youchenlee** [comment]
@premier213 It would be nice if you provide a browser console log, otherwise it's impossible to debug.

**Comment by premier213** [comment]
![2016-02-22_19-57-24](https://cloud.githubusercontent.com/assets/4321174/13224605/94740fce-d99e-11e5-863f-bd7e18bb4275.jpg)

**Comment by tekinerten** [comment]
I have the same error. I couldn't have solved it yet

**Comment by youchenlee** [comment]
It seems happened to me once when I install laravel-filemanager on a clean laravel. But I cannot reproduce it anymore.

Would you guys please provide me some reproduce steps?
Thanks.

**Comment by tekinerten** [comment]
my mistake. I solved thank you

**Comment by meeprakash25** [comment]
i am having the same issue here, laravel-ckeditor is not loading in browser, i followed the installation process as described here https://github.com/UniSharp/laravel-ckeditor#publish-the-resources,

Also when i go to the ckeditor link from view source, that is not working

**Comment by Mohsing511** [comment]
> my mistake. I solved thank you

how did you solved it

**Comment by bhensonweb** [comment]
I had this problem too.
After adding the Service Provider to my config/app.php config file I had to clear my config cache:
`php artisan config:cache`
...and then publish the assets after that.

**Comment by Mohsing511** [comment]
Thanks UniSharp/laravel-ckeditor
